.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. cedicoin_qt test_cedicoin_qt
clean: FORCE
	$(MAKE) -C .. cedicoin_qt_clean test_cedicoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_cedicoin_qt_check
cedicoin-qt cedicoin-qt.exe: FORCE
	 $(MAKE) -C .. cedicoin_qt
